module.exports = {
  UPDATE_USER: 'UPDATE_USER',
  PASSWORD_RESET: 'PASSWORD_RESET',
  UPDATE_PASSWORD: 'UPDATE_PASSWORD',
  DUPLICATE_USER: 'DUPLICATE_USER',
  LACK_INFO_FIELDS: 'LACK_INFO_FIELDS',
  USER_NOT_FOUND_OR_WRONG_PASSWORD: 'USER_NOT_FOUND_OR_WRONG_PASSWORD',
  CONTACT_DEVELOPER: 'CONTACT_DEVELOPER',
  DATA_ANALYSIS: 'DATA_ANALYSIS',
  OVERALL_ANALYSIS: 'OVERALL_ANALYSIS'
}